/**
 * Public Management contracts and semantic service; HTTP, OpenAPI, client,
 * and CLI projections remain outside this package.
 * @packageDocumentation
 */

export {
  FIRST_CLAIM_LIFETIME_MS,
  MANAGEMENT_API_BASE_PATH,
  MANAGEMENT_CONTRACT_VERSION,
  MANAGEMENT_DISCOVERY_PATH,
  SESSION_LIFETIME_MS,
  claimRequestSchema,
  claimResponseSchema,
  capabilityGraphSchema,
  hostReadModelSchema,
  loginRequestSchema,
  loginResponseSchema,
  managementDiscoverySchema,
  managementProblemSchema,
  lineageContextRefSchema,
  resourceRefSchema,
  readinessSchema,
  runtimeBindingSnapshotSchema,
  runtimeCapabilityGraphEntrySchema,
  runtimeCapabilityProvisionSnapshotSchema,
  runtimeCapabilityRequirementSnapshotSchema,
  runtimeGraphEdgeSchema,
  runtimeGraphSchema,
  runtimeProvisionSnapshotSchema,
  runtimeRequirementSnapshotSchema,
  runtimeSystemSnapshotSchema,
  systemActionDefinitionSchema,
  systemActionExecuteResultSchema,
  systemChangePlanSchema,
  systemStatusSchema,
} from "./contracts.js";
export type {
  AdministratorBootstrapState,
  AdministratorId,
  AdministratorVerifier,
  CapabilityGraphReadModel,
  ClaimRequest,
  ClaimResponse,
  CompatibilityDescriptor,
  ContractRange,
  EvidenceRef,
  FirstAdministratorClaim,
  FirstAdministratorClaimId,
  FirstClaimMaterial,
  HostReadModel,
  HostReadModelData,
  JsonSchemaRef,
  LineageContextRef,
  LoginRequest,
  LoginResponse,
  ManagementDiscovery,
  ManagementHttpState,
  ManagementHostState,
  ManagementProblemDetails,
  ManagementDigest,
  ProductSemanticId,
  Readiness,
  ReadinessData,
  ReadModelEnvelope,
  ResourceRef,
  RuntimeBindingSnapshot,
  RuntimeCapabilityGraphEntry,
  RuntimeCapabilityProvisionSnapshot,
  RuntimeCapabilityRequirementSnapshot,
  RuntimeGraphEdge,
  RuntimeGraphReadModel,
  RuntimeGraphReadModelData,
  RuntimeIntrospectionSnapshot,
  RuntimeOperatingMode,
  RuntimeProvisionSnapshot,
  RuntimeRequirementSnapshot,
  RuntimeSystemSnapshot,
  RuntimeSystemActualState,
  RuntimeSystemRole,
  ServerSession,
  ServerSessionId,
  SystemStatus,
  SystemStatusData,
  SystemActionDefinition,
  SystemActionExecuteResult,
  SystemActionId,
  SystemChangePlan,
  SystemChangePlanId,
  TargetPrecondition,
  CapabilityGraphReadModelData,
} from "./contracts.js";
export { createManagementService } from "./service.js";
export type {
  ManagementProjectionSource,
  ManagementService,
  ManagementServiceOptions,
} from "./service.js";
export {
  managementHttpStatus,
  managementProblem,
  toManagementProblemDetails,
  contractUnsupportedProblem,
  invalidInputProblem,
} from "./problems.js";
