/**
 * Public shared Foundation vocabulary for canonical values, identities,
 * lifecycle roots, Problems, and data governance without runtime side effects.
 * @packageDocumentation
 */

export {
  canonicalizeJson,
  snapshotCanonicalJson,
  type CanonicalJsonSnapshot,
  type CanonicalJsonValue,
} from "./canonical-json.js";
export { digestCanonicalJson, type Sha256Digest } from "./digest.js";
export {
  asContentDigest,
  createBootId,
  createActivityId,
  createContinuityEpochId,
  createEvidenceId,
  createHostOwnershipToken,
  createInstallationId,
  createInstanceId,
  createUuidV7Id,
  isSha256Hex,
  isUuidV7,
  parseContentDigest,
  parseBootId,
  parseActivityId,
  parseContinuityEpochId,
  parseEvidenceId,
  parseHostOwnershipToken,
  parseInstant,
  parseInstallationId,
  parseInstanceId,
  parseUuidV7Id,
  SHA256_HEX_PATTERN,
  UUID_V7_PATTERN,
  formatInstant,
  type Branded,
  type ActivityId,
  type BootId,
  type ContentDigest,
  type ContinuityEpochId,
  type EvidenceId,
  type InstallationId,
  type InstanceId,
  type HostOwnershipToken,
  type UuidV7Id,
  type Instant,
} from "./identity.js";
export type { RetentionClass, Sensitivity } from "./data-governance.js";
export {
  createCapabilityId,
  createContributionId,
  asDurableCodeVersion,
  createMicroSystemId,
  createMicroSystemInstanceId,
  createProviderId,
  createServiceId,
  createWorkItemId,
  NAMESPACED_ID_PATTERN,
  parseCapabilityId,
  parseContributionId,
  parseDurableCodeVersion,
  parseMicroSystemId,
  parseMicroSystemInstanceId,
  parseProviderId,
  parseServiceId,
  parseWorkItemId,
  type CapabilityId,
  type ContributionId,
  type DurableCodeVersion,
  type MicroSystemId,
  type MicroSystemInstanceId,
  type NamespacedId,
  type PackageGenerationId,
  type ProductGenerationId,
  type ProviderId,
  type ServiceId,
  type WorkItemId,
} from "./runtime-identity.js";
export { LIFECYCLE_ROOT_IDS, type LifecycleRootId } from "./lifecycle-root.js";
export { POSTGRES_INTEGER_MAX } from "./numeric.js";
export {
  createProblem,
  createProblemError,
  ProblemError,
  type FieldError,
  type Problem,
  type ProblemInit,
  type RetryClass,
} from "./problem.js";
